name: CI

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
    branches:
      - main
  pull_request:

jobs:
  scala:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '1.8', '1.11' ]
        scala: [
            { version: '2.12.13' },
            { version: '2.12.12' },
            { version: '2.12.11' },
            { version: '2.12.10' },
            { version: '2.12.9' },
            { version: '2.12.8' },
            { version: '2.13.5' },
            { version: '2.13.4' },
            { version: '2.13.3' },
            { version: '2.13.2' },
            { version: '2.13.1' },
            { version: '2.13.0' }
          ]
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Scala env
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@${{ matrix.java }}

      - name: run tests
        run: sbt ++${{ matrix.scala.version }} test
